### ISSUE TITLE
Component: Quick Links

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/census2020#27]
Example from https://www.lacounty.gov/census2020/ :

![Screen Shot 2019-11-05 at 11 25 54 PM](https://user-images.githubusercontent.com/5697474/68270780-2652ba80-0024-11ea-9006-0574a6dbcc6e.png)

**Comment by tara-olson-atx** [comment]
For this section, I'd like to have the following as Quick Links and Homepage Heading Tabs. @JLawler512 - Weigh in if you feel differently please.

****Quick Links/Website Headings:**

Link/Heading 1. **- About the 2020 Census****
_(On this page, the following text is what I'm envisioning:)_
**About the 2020 Census**
The City of Austin and Travis County have launched a Census Outreach Campaign to ensure residents are educated and prepared for the 2020 Census. Every ten years the U.S. Census Bureau oversees a survey of the whole country to determine population totals and breakdowns by sex, age, race and other factors. Next year, between March and July, individuals will be able to respond online, by phone, or by mail.
 
The Census information guides the allocation of more than $800 billion in federal funding to programs across the U.S. that are crucial to the well-being of families and communities. If Texas residents are undercounted by even 1% Texas could lose at least $300 million per year.
 
If people in Austin and Travis County go uncounted then the community could lose significant funding for Medicaid, Medicare, State Children’s Health Insurance (CHIP), Section 8 Housing, Head Start, National School Lunch Program, Special Education Grants and highway planning and construction.
 
Counting everyone can be logistically challenging. Very young children, immigrants, people who live in rural areas, people of color, people who move residences more frequently, and people who face language barriers, are often harder to count.

The 2020 Census is an opportunity to get as many people as possible to participate in order to shape our future. Your Census responses are safe and secure. Information collected as part of the 2020 Census cannot be shared with or by other governmental agencies or used against you in any way.

**When Is The Census?**
_(This is where I'm envisioning the Timeline graphic with the following text below)_
Invitations Mailed
MARCH 12-20
Reminder Letters
MARCH 16-24
Reminder Postcard
MARCH 26 - APRIL 3
Census Day
APRIL 1
Hard Copy Census Mailed
APRIL 8-16
Final Postcards Mailed
APRIL 20-27
Don’t Delay! Be sure to fill out your census form before April 30th.

**How To Complete the Census**
Every person in the country is required to fill out the 2020 Census form. Luckily, you have three ways to respond.

Video and printed guides will also be available in 59 non-English languages, and there will be a video in American Sign Language, plus a printed guide in braille.

Whichever you choose, just make sure you fill out the form!
_By Mail - Icon_
**By Mail**
The paper Census form will be available in English and Spanish languages and can be mailed back to the U.S. Census Bureau.

_By Phone - Icon_
**By Phone**
The Census can be completed by phone in 13 languages including Telecommunication Device for the Deaf.

_By Computer - Icon_
**Online**
For the first time, the Census form will be available to complete online in 13 languages. Need access to a computer? Visit any Austin Public Library Branch for details or call 512-974-7400.

Link/Heading 2. **Why the 2020 Census Matters**
_(On this page, the following text is what I'm envisioning:)_
**Why The Census Matters**

There is a lot at stake in the 2020 Census and our communities can't afford an undercount. Essential neighborhood resources throughout Austin and Travis County rely on federal funding that is based on information collected during the Census. 

We only get one chance every 10 years at achieving a full count. This data will inform important policy decisions and determine federal funding allocations for a decade. In 2010, significant undercounts occurred across local communities in Texas, including in portions of: Large metropolitan areas, College towns, Rural counties, and Communities along the Texas/Mexico border.

The mail-in self-response rate for Travis County in the 2010 Census was 75.9%, which required a costly and difficult in-person follow-up for the remaining 24.1% of residents. Historically, children under 5 have been undercounted, 2.1% of children under the age of five in Travis County were undercounted in the 2010 Census. 

Our most recent research estimates that reaching Travis County residents in hard-to-count neighborhoods at a basic level of $2 dollars per person (mailers, a couple public forms, and some level of direct outreach) would cost at least $742,000 dollars. Most recent data as of 2017 shows that 11.6% of the county’s households had either no internet access or dial-up only.

**Historically Undercounted Communities in Austin and Travis County**
Texas is at risk of an even larger undercount in 2020. Today, 25% of Texans (over 6 million people) live in hard-to-count neighborhoods, where past self-response rates have been relatively low. Today in Travis County, 32% (over 370,000 people) of the population live in hard-to-count neighborhoods. An undercount means Texas is not getting its fair share of funding and representation since not everyone living in our state was counted. View the map below to see if your neighborhood is at risk of being undercounted. 

**VIEW MAP** _BUTTON HERE_

Link/Heading 3. **Frequently Asked Questions**
_(On this page, the following text is what I'm envisioning:)_

**1. Why is it important for everyone to be counted in the Census?**
Some federal funds, grants, and support to states, counties and communities are based on population.
It is critical for everyone to be counted, regardless of immigration status. When you respond to the Census, you help your community get its fair share of federal funds.
Businesses use Census data to decide where to build factories, offices and stores, and this creates jobs.
Developers use Census data to build new homes and revitalize neighborhoods.
Local governments use Census data for public safety and emergency preparedness.

**2. How do you get counted?**
Starting mid-March 2020, each household will receive a postcard in the mail informing them of the options for filling out the Census questionnaire. That includes online, by phone, or with a paper form.
Households that do not fill out the questionnaire during the self-response period will be contacted by the U.S. Census Bureau during Non-Response Follow-Up.
March 12-20: Households will receive an invitation to respond online to the 2020 Census. Some households will also receive paper questionnaires.
March 16-24: A reminder letter will be sent.
If you still have not responded:
March 26-April 3: A reminder postcard will be sent to households that have not responded.
April 8-16: A reminder letter and paper questionnaire will be sent.
April 20-27: A final reminder postcard before the U.S. Census Bureau follows up in person.
U.S. Census Bureau enumerators may contact households that submit partially filled-out questionnaires in an effort to obtain complete answers.

**3. What should Texans be aware of when filling out the Census?**
It is critical to be cautious of any requests that seem suspicious.
The U.S. Census Bureau will never ask for the following:

- Payment to fill out the questionnaire

- Social Security number

- Financial information

U.S. Census Bureau field staff will always show a valid Census Bureau ID. You can confirm that they are a U.S. Census Bureau employee by entering their name into the Census Bureau Staff Search or by contacting the Texas Regional Office at 1-800-852-6159.

It is a federal crime to impersonate a federal official, and anyone who violates this law is subject to imprisonment.

**4. Is private information protected?**

- The United States Census Bureau (USCB) is required by law to protect any personal information it collects and keep it confidential.

- The U.S. Census Bureau is bound by Title 13 of the United States Code. These laws not only provide the Bureau with authority for its work, but also stipulate strong protections for the information the Census collects from individuals and businesses.

- The U.S. Census Bureau uses responses to produce statistics.

- Private information may not be published when it is collected. After 72 years, it may be published for historical purposes by the National Archives. It is against the law to disclose or publish any private information that identifies an individual or business, such as names, addresses (including GPS coordinates), Social Security numbers, and telephone numbers.

- Answers cannot be used for law enforcement purposes or to determine personal eligibility for government benefits.

- Personal information cannot be used against respondents for the purposes of immigration enforcement.

- U.S. Census Bureau employees are sworn to protect confidentiality. Every person with access to data is sworn for life to protect personal information and understands that the penalties for violating this law are applicable for a lifetime.

- Violating confidentiality or sharing the information other than for statistical purposes is a serious federal crime. Anyone who violates this law will face severe penalties, including a federal prison sentence of up to five years, a fine of up to $250,000, or both.

**6. Will the 2020 Census include a question about Citizenship?**
The 2020 Census questionnaire will NOT include a question about an individual’s citizenship status. Everyone, regardless of their immigration status, has certain basic rights. For those who have concerns about opening your doors, there are other ways you can participate. You can participate from the comfort of your home online and over the phone, or at community run assistance center. Please complete your Census questionnaire. An incomplete questionnaire may increase your chances of nonresponse follow-up by the U.S. Census Bureau. Households will receive an invitation to respond online to the 2020 Census beginning March 12, 2020. Your participation is vital, and your information is protected.

**7. What is the Austin-Travis County Complete Count Committee doing to encourage participation?**

- The Austin-Travis County Complete Count Committee is supporting a coordinated outreach and communication effort focused on reaching the hard-to-count (HTC) population. This Committee is collaborating and leveraging support from local governments, regional and statewide community-based organizations, nonprofit, education, and other agencies to ensure the hardest to count communities are reached. Communication efforts will aim to help our residents understand that their information will remain private and dispel misinformation. 

- Take a look at our Interactive Map for a list of upcoming events to get involved or to learn more, e-mail census@traviscountytx.gov. 

Link/Heading 4. **Stay Connected**

Our goal is to achieve a full and complete count of all Texans. Please help spread the word and ensure you, your family, neighbors, and friends are all counted!

For more information, contact census@traviscountytx.gov.

You can also visit the [Austin-Travis County Complete Count Committee Facebook page](https://www.facebook.com/Austin-Travis-County-Complete-Count-Committee-289680787280/) for the latest information.
